version: '3.4'
services:
  front:
    build: "./client"
    command: npm run start
    volumes:
      - ./client/src:/app/front/src
      - ./client/public:/app/front/public
      - ./client/tailwind.config.js:/app/front/tailwind.config.js
    working_dir: /app/front
    links:
      - "back"
    ports:
      - "3000:3000"
  back:
    build: "./server"
    working_dir: /app/back
    command: npm run dev
    volumes:
      - type: bind
        source: ./server/src
        target: /app/back/src
      - ./server/env:/app/back/.env
      - ./server/uploads/thumbnails:/uploads/thumbnails # Ajout du volume pour les miniatures
      - ./server/uploads/videos:/uploads/videos # Ajout du volume pour les vidéos
      - ./server/uploads/shorts:/uploads/shorts # Ajout du volume pour les shorts
    networks:
      - bdd-back
    ports:
      - "5000:5000"
    
  bdd:
    image: mariadb
    networks:
      - bdd-back
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: coditube
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
  adminer:
    image: adminer
    networks:
      - bdd-back
    ports:
      - 8080:8080
  live:
    build: ./live-server
    working_dir: /app/live
    networks:
      - bdd-back
    volumes:
      - ./live-server/app.js:/app/live/app.js
    command: node app.js
    ports: 
    - 1936:1936
    - 8090:8090
    
networks:
  bdd-back:
    driver: bridge
  